### ISSUE TITLE
Investigate the status of Papyrus

### ISSUE THREAD

**Issue by vssesti** [ESOM-2017-1/frost-lotus#6]
We need to investigate how Papyrus currently stands and how well it works with whatever is the most recent version of Eclipse. Afterwards, some trivial examples should be executed on it.

**Comment by pedroeml** [comment]
I found papyrus at: http://www.eclipse.org/papyrus/download.html
There is also an installation tutorial for installing papyrus from eclipse Mars: https://wiki.eclipse.org/Papyrus-RT/User/User_Guide/Installation#Install_Papyrus
For eclipse Neon, I found the following steps below from https://www.eclipse.org/forums/index.php/t/1082246/

1. Help -> Install new software
2. In the "Work with" section of "Available Software", select the release of interest (e.g., Neon)
3. In the type filter, type "Papyrus"
4. Select "Papyrus UML" and, optionally, the model comparison feature.
5. Select [Next]
6. Select [Next] again to the details
7. Accept the licenses and click [Finish].

Since I'm using eclipse Neon, I followed these steps and after installation the eclipse's welcome screen should be like this:

![screenshot from 2017-05-08 10-36-32](https://cloud.githubusercontent.com/assets/20287773/25806714/8704e9e8-33da-11e7-857c-8948ef76d67f.png)
